# Site settings
name: "Lingnik : Taylor J. Meek"
title: Taylor J. Meek
email: taylor.meek@gmail.com
description: "Taylor is a senior software engineering manager who used to write software, do things with machine learning and linguistics, and mess around with servers. He fancies the outdoors and is grateful that Portland, OR has so much of it. He currently works for Heroku, a Salesforce company, where he leads the Heroku Tools Team--a stellar group of Ruby and Go engineers who build internal tools and services that help our colleagues focus on what they do best. Although he enjoys talking about himself in the third person, he'd rather be talking to you face-to-face. Stupid pandemic."
icon: "/favicon.ico"
baseurl: ""
url: "http://lingnik.com"
username: lingnik
timezone: America/Los_Angeles
locale: en_us

author:
  facebook: lingnik
  twitter: lingnik
# googleplus: lingnik
#fb_admins
#fb_appid

source: ./
destination: ../master
safe: false

exclude: build.bash

#Build settings
markdown: kramdown
permalinks: pretty
