# Site settings
name: "Lingnik : Taylor J. Meek"
title: Taylor J. Meek
email: taylor.meek@gmail.com
description: "Taylor is a software engineer and linguist living in Portland, OR who fancies the outdoors. He currently works for Iberdrola Renewables, the world's largest wind power owner-operator, as a SCADA analyst."
baseurl: ""
url: "http://lingnik.com"
username: lingnik
timezone: America/Los_Angeles

source: ./
destination: ../master
safe: false

exclude: build.bash

#Build settings
markdown: kramdown
permalinks: pretty
