# Site settings
name: "Lingnik : Taylor J. Meek"
title: Taylor J. Meek
email: taylor.meek@gmail.com
description: "Taylor is a staff software engineer at Aptible, where he builds Managed AI services for a HIPAA-compliant PaaS. He spent seven years leading engineering teams at CloudBolt, Heroku, and Salesforce before deciding he missed writing code more than he missed expense reports. He fancies the outdoors and is grateful that Portland, OR has so much of it. Although he enjoys talking about himself in the third person, he'd rather be talking to you face-to-face."
icon: "/favicon.ico"
baseurl: ""
url: "http://lingnik.com"
username: lingnik
timezone: America/Los_Angeles
locale: en_us

author: Taylor J. Meek
twitter: lingnik
# googleplus: lingnik
#fb_admins
#fb_appid

exclude:
  - build.bash
  - Gemfile
  - Gemfile.lock
  - vendor

#Build settings
permalink: pretty
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-redirect-from
